version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: psdb
    volumes:
      - mysql-data-vol:/var/lib/mysql
    networks:
      - psnet
    ports:
      - '3306:3306'
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=pageseeder'
      - 'MYSQL_USER=pageseeder'
      - 'MYSQL_PASSWORD=pageseederDB123'
    healthcheck:
      test: ["CMD", "mysql" ,"-uroot", "-ppassword"]
      timeout: 20s
      retries: 10

  pageseeder:
    depends_on:
      - mysql
    image: alletterchan/pageseeder
    container_name: ps
    volumes:
      - ps-data-vol-config:/opt/pageseeder/webapp/WEB-INF/config
      - ps-data-vol-state:/opt/pageseeder/webapp/WEB-INF/state
      - ps-data-vol-documents:/opt/pageseeder/documents
    networks:
      - psnet
    restart: always
    links:
      - mysql:psdb
    ports:
      - '8080:8080'
      - '8282:8282'

volumes:
  mysql-data-vol: {}
  ps-data-vol-config: {}
  ps-data-vol-state: {}
  ps-data-vol-documents: {}

networks:
  psnet:
    driver: bridge